env = Environment()
env['CPPPATH'] = Dir('.').abspath
env['PCHSTOP'] = 'stdafx.hpp'
#env['PCH'] = env.PCH('stdafx.cpp')[0]

env['CCFLAGS'] = '-Wall -O2 -std=c++11'

bus = Glob('bus/*.cpp')
cpu = Glob('r3051/*.cpp')
gpu = Glob('gpu/*.cpp')
spu = Glob('spu/*.cpp')

env.Program('psxact', Glob('*.cpp') +
  bus +
  cpu +
  gpu +
  spu)
