env = Environment()
env['CPPPATH'] = Dir('.').abspath
env['PCHSTOP'] = 'stdafx.hpp'
env['PCH'] = env.PCH('stdafx.cpp')[0]

bus = Glob('bus/*.cpp')
cpu = Glob('r3051/*.cpp')
gpu = Glob('gpu/*.cpp')
spu = Glob('spu/*.cpp')

env.Program('psxact', Glob('*.cpp') +
  bus +
  cpu +
  gpu +
  spu)
