# compiler configurations

def clConfiguration(env):
  env['CCFLAGS'] = '/Ox /O2'
  env['PCHSTOP'] = 'stdafx.hpp'
  env['PCH'] = env.PCH('stdafx.cpp')[0]

def gccConfiguration(env):
  env['CCFLAGS'] = '-Wall -O2 -std=c++11'

def mingwConfiguration(env):
  return gccConfiguration(env)

# environment initialization

env = Environment()
env['CPPPATH'] = Dir('.').abspath

if env['CC'] == 'cl': clConfiguration(env)
if env['CC'] == 'gcc': gccConfiguration(env)
if env['CC'] == 'mingw': gccConfiguration(env)

# modules to build

modules = ['bus', 'gpu', 'spu', 'r3051']
sources = [Glob(module + '/*.cpp') for module in modules]

env.Program('psxact', sources + ['psxact.cpp', 'system.cpp'])
